name = "__PROJECT_CODE__"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Workers の開発用サブドメインを有効化
workers_dev = true

# Astro SSR のエントリーポイント
main = "./dist/_worker.js"

# 静的アセットの配信設定
[assets]
directory = "./dist"
binding = "ASSETS"